import type { NewsSource } from "./types";

export const NEWS_SOURCES: NewsSource[] = [
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    feedUrl: "https://finance.yahoo.com/news/rssindex",
    homepageUrl: "https://finance.yahoo.com/news/",
    category: "Markets",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "cnbc-markets",
    name: "CNBC Markets",
    feedUrl: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    homepageUrl: "https://www.cnbc.com/markets/",
    category: "Markets",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "marketwatch-top",
    name: "MarketWatch Top Stories",
    feedUrl: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    homepageUrl: "https://www.marketwatch.com/",
    category: "Markets",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "marketwatch-realtime",
    name: "MarketWatch Real-time Headlines",
    feedUrl: "https://feeds.content.dowjones.io/public/rss/mw_realtimeheadlines",
    homepageUrl: "https://www.marketwatch.com/latest-news",
    category: "Markets",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "cnbc-earnings",
    name: "CNBC Earnings",
    feedUrl: "https://www.cnbc.com/id/15839135/device/rss/rss.html",
    homepageUrl: "https://www.cnbc.com/earnings/",
    category: "Companies",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "cnbc-technology",
    name: "CNBC Technology",
    feedUrl: "https://www.cnbc.com/id/19854910/device/rss/rss.html",
    homepageUrl: "https://www.cnbc.com/technology/",
    category: "Companies",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "cnbc-finance",
    name: "CNBC Finance",
    feedUrl: "https://www.cnbc.com/id/10000664/device/rss/rss.html",
    homepageUrl: "https://www.cnbc.com/finance/",
    category: "Markets",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "globenewswire-public",
    name: "GlobeNewswire Public Companies",
    feedUrl:
      "https://www.globenewswire.com/RssFeed/orgclass/1/feedTitle/GlobeNewswire%20-%20News%20about%20Public%20Companies",
    homepageUrl: "https://www.globenewswire.com/en/search/organization/public",
    category: "Companies",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "nyt-business",
    name: "New York Times Business",
    feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    homepageUrl: "https://www.nytimes.com/section/business",
    category: "Companies",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "nyt-economy",
    name: "New York Times Economy",
    feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml",
    homepageUrl: "https://www.nytimes.com/section/business/economy",
    category: "Economy",
    trustTier: "public-rss",
    enabled: true,
  },
  {
    id: "investopedia-markets",
    name: "Investopedia Markets",
    feedUrl:
      "https://www.investopedia.com/feedbuilder/feed/getfeed/?feedName=rss_headline",
    homepageUrl: "https://www.investopedia.com/markets-news-4427704",
    category: "Markets",
    trustTier: "public-rss",
    enabled: false,
  },
  {
    id: "sec-press",
    name: "SEC Press Releases",
    feedUrl: "https://www.sec.gov/news/pressreleases.rss",
    homepageUrl: "https://www.sec.gov/news/pressreleases",
    category: "Regulation",
    trustTier: "official",
    enabled: true,
  },
  {
    id: "sec-statements",
    name: "SEC Speeches and Statements",
    feedUrl: "https://www.sec.gov/news/speeches-statements.rss",
    homepageUrl: "https://www.sec.gov/news/speeches-statements",
    category: "Regulation",
    trustTier: "official",
    enabled: true,
  },
  {
    id: "federal-reserve-press",
    name: "Federal Reserve Press Releases",
    feedUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
    homepageUrl: "https://www.federalreserve.gov/newsevents/pressreleases.htm",
    category: "Policy",
    trustTier: "official",
    enabled: true,
  },
  {
    id: "federal-reserve-speeches",
    name: "Federal Reserve Speeches",
    feedUrl: "https://www.federalreserve.gov/feeds/speeches.xml",
    homepageUrl: "https://www.federalreserve.gov/newsevents/speeches.htm",
    category: "Policy",
    trustTier: "official",
    enabled: true,
  },
  {
    id: "treasury-press",
    name: "U.S. Treasury Press Releases",
    feedUrl: "https://home.treasury.gov/news/press-releases/rss",
    homepageUrl: "https://home.treasury.gov/news/press-releases",
    category: "Policy",
    trustTier: "official",
    enabled: false,
  },
  {
    id: "bls-releases",
    name: "Bureau of Labor Statistics",
    feedUrl: "https://www.bls.gov/feed/news_release/all.rss",
    homepageUrl: "https://www.bls.gov/news.release/",
    category: "Economy",
    trustTier: "official",
    enabled: false,
  },
];

export const enabledSources = NEWS_SOURCES.filter((source) => source.enabled);
